name: Build and deploy Node.js app to Azure Web App - assemblia-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: npm install and build
        run: |
          npm install
          npm run build
        working-directory: sentiment-backend  # Changez selon votre vraie structure
        
      - name: Debug - List build contents
        run: |
          echo "=== Contenu du dossier racine ==="
          ls -la sentiment-backend/
          echo "=== Contenu du dossier .next ==="
          ls -la sentiment-backend/.next/ || echo "Pas de dossier .next"
          echo "=== Contenu du dossier .next/standalone ==="
          ls -la sentiment-backend/.next/standalone/ || echo "Pas de dossier standalone"
          echo "=== Contenu du dossier .next/static ==="
          ls -la sentiment-backend/.next/static/ || echo "Pas de dossier static"
        
      - name: Prepare release folder for standalone deployment
        run: |
          mkdir -p release
          # Copier le build standalone
          cp -r sentiment-backend/.next/standalone/* release/
          # Créer le dossier .next dans release
          mkdir -p release/.next
          # Copier les fichiers statiques seulement s'ils existent
          if [ -d "sentiment-backend/.next/static" ]; then
            cp -r sentiment-backend/.next/static release/.next/static
          fi
          # Copier public seulement s'il existe
          if [ -d "sentiment-backend/public" ]; then
            cp -r sentiment-backend/public release/public
          fi
          # Copier package.json
          cp sentiment-backend/package.json release/
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: node-app
          
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'assemblia-backend'
          slot-name: 'Production'
          package: node-app
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AC1767BB6D594B1B83E89216B78C0DC8 }}
