import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from 'react';
import { CssBaseline, ThemeProvider, createTheme, Container } from '@mui/material';
import NavBar from '../../components/NavBar';
import { Open_Sans } from 'next/font/google';

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '600', '700'], 
  display: 'swap',
});

const theme = createTheme();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Assembl'IA",
  description: "Generated by next app",
};

import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <body className={openSans.className}>
        <NavBar /> {/* Client component */}
        <Container maxWidth={false} sx={{ mt: 2, px: { xs: 1, sm: 3, md: 6 } }}> 
          {children}
        </Container>
      </body>
    </html>
  );
}
