import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from 'react';
import { CssBaseline, ThemeProvider, createTheme, Container } from '@mui/material';
import NavBar from '../../components/NavBar';
import { Open_Sans } from 'next/font/google';

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // choisis les graisses que tu veux
  display: 'swap',
});

const theme = createTheme();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <body className={`${geistSans.variable} ${geistMono.variable}`}>
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }
// export default function RootLayout({ children }: { children: ReactNode }) {
//   return (
//     <html lang="fr">
//       <body>
//         <ThemeProvider theme={theme}>
//           <CssBaseline />
//           <NavBar />
//           <Container maxWidth="lg" sx={{ mt: 4 }}>
//             {children}
//           </Container>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }


// import './globals.css';
import { Inter } from 'next/font/google';
// import NavBar from '/mnt/d/Assembl-IA-Streamlit/sentiment-frontend/components/NavBar';

// import { Container } from '@mui/material';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <body className={openSans.className}>
        <NavBar /> {/* Client component */}
        <Container maxWidth={false} sx={{ mt: 2, px: { xs: 1, sm: 3, md: 6 } }}> 
          {children}
        </Container>
      </body>
    </html>
  );
}
